version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: miniecommerce_development
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - 6379:6379
volumes:
  db_data:
